apiVersion: apps/v1
kind: Job
metadata:
  generateName: maint-page-up
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: springboot-app-rama
  name: springboot-app-rama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-rama
  template:
    metadata:
      labels:
        app: springboot-app-rama
    spec:
      containers:
      - name: my-springboot-app-rama
        image: 490167669940.dkr.ecr.ap-southeast-1.amazonaws.com/eks-frontend-app-deployment:frontend-32
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app-rama
    k8s-app: springboot-app-rama
  name: springboot-app-rama
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app-rama
